### ISSUE TITLE
Scroll performance improvements

### ISSUE THREAD

**Issue by crisbeto** [js-org/stats.js.org#5]
There's quite a lot of repainting going on when scrolling, this is mostly because the `background-attachment: fixed;` and the fixed header and footer. This can get improved easily with the following CSS:

The biggest offender is the `background-attachment`, so switching this:

``` css
html.no-js, html.ie8, html.bg {
    background: url("https://js.org/img/bg.png") #ffb400 repeat-y fixed;
}
```

to this fixes quite a lot: 

``` css
html.no-js, html.ie8, html.bg {
    background: url("https://js.org/img/bg.png") #ffb400 repeat-y;
}
```

Another easy fix is adding `transform: translateZ(0)` to `.afix` and `#tbl thead:after, #tbl tfoot:after`.
